### ISSUE TITLE
Opening URL in a new Tab

### ISSUE THREAD

**Issue by Vamsheeth** [Peekobot/peekobot#18]
## Current Behavior:
- When Someone clicks on a Link, It is opening in a same tab which is making users not able to proceed with other options provided.

## Expected Behavior:
- When user clicks on Link, There should be a configuration to set to open the Link in a New Tab.

## Ref Links:
- https://stackoverflow.com/questions/66176085/how-to-open-url-in-new-tab-from-javascript-script/66176479#66176479
- https://wepython.cc/thread-5766582.htm

**Comment by rosswintle** [comment]
Thanks for the suggestion.

I won't add this to the default Peekobot code, but you can modify it yourself.

I'd suggest adding a `target` property to the options for a step:

```
options: [
            {
                text: 'Tea',
                url: 'http://example.com/tea',
                target: '_blank'
            }
        ]
```

and then adding this in when Peekobot creates the options. So on about line 40 do:

```
if (option.url) {
    button.href = option.url;
	button.target = option.target;
} else {
```

Hope that helps. Thanks for using Peekobot! 🤖
