### ISSUE TITLE
Is this repository still alive?

### ISSUE THREAD

**Issue by gzuuus** [Peekobot/peekobot#21]
Is this repository still alive or has it been discontinued?

**Comment by rosswintle** [comment]
The code still works... if that's what you mean?

How can I help?

**Comment by gzuuus** [comment]
Yes! it works perfectly, I've been testing it a bit, I'm now developing inline input fields for custom answers and playing a bit with what could be menus, numbered steps representing sections or utilities. I was just wondering why I see the last commit in 2020 and the unmerged pr's.

**Comment by rosswintle** [comment]
I know it's unusual for software but I kinda consider Peekobot "finished".

Totally happy for you to copy and make your own thing from it.

**Comment by gzuuus** [comment]
Ok! thanks! 🧡
