### ISSUE TITLE
Add <meta charset="UTF-8"> for emojis and more

### ISSUE THREAD

**Issue by nikas-belogolov** [Peekobot/peekobot#8]

**Comment by rosswintle** [comment]
Thanks. Where should this be put? Doesn't this meta tag go in the HTML `<head>`?

Is this just something to add to the documentation?

**Comment by nikas-belogolov** [comment]
> Thanks. Where should this be put? Doesn't this meta tag go in the HTML `<head>`?
> 
> Is this just something to add to the documentation?

add this in the documentation and in the example

**Comment by rosswintle** [comment]
Ah yes. Thank you. I'm so used to my CMS or server doing this for me.

Added to the sample bot and to the README.

Thanks for all your input!
